# env
env: drq-robosuite
# train
lr: 1e-3
seed: 10
# eval
num_eval_episodes: 2
# misc
save_video: true
device: cuda
# observation
image_size: 84
image_pad: 4
horizon: 500 #bogus value but needed 
system: real #sim for the mujoco stuff, and "real" for franka

# key changes 
demos: 50
episodeLength: 1000
frame_stack: 3
lowdim_stack: 10 #how many past lowdim stuff do you want to conatenate
runName: TestPs3_${demos}
demo_root: /iris/u/maxjdu/communal_demos/

# audio stuff 
audio_steps: ??
audio_bins: ??
audio_shape: ?? 

#loading from partially-completed demos 
load_demo: false 
demo_file: bogus #FrankaKeysScratch_${demos}/demos_backup.pkl

#Other hyperparameters
sparseProp: 0.75
raw_lowdim: 7

# agent configuration
agent:
  name: drq
  class: drq.DRQAgent
  params:
    obs_shape: ??? # to be specified later
    action_shape: ??? # to be specified later
    action_range: ??? # to be specified later
    lowdim_dim: ??? #to b e specified later
    device: ${device}
    encoder_cfg: ${encoder}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    discount: 0.99
    init_temperature: 0.1
    lr: ${lr}
    actor_update_frequency: 2
    critic_tau: 0.01
    critic_target_update_frequency: 2
    batch_size: ${batch_size}
    log_frequency: 20

critic:
  class: drq.Critic
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_dim: 1024
    hidden_depth: 2

actor:
  class: drq.Actor
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-10, 2]

encoder:
  class: drq.Encoder
  params:
      obs_shape: ${agent.params.obs_shape}
      feature_dim: 50
      lowdim_dim: ${agent.params.lowdim_dim}
      num_layers: 4
      num_filters: 32
      output_dim: 35
      output_logits: False

log_dir: /iris/u/maxjdu/communal_demos/${runName}/
# hydra configuration
hydra:
  name: ${env}
  run:
    dir: ${log_dir} #./demos/${runName}/
