# env
env: drq-robosuite
# IMPORTANT: if action_repeat is used the effective number of env steps needs to be
# multiplied by action_repeat in the result graphs.
# This is a common practice for a fair comparison.
# See the 2nd paragraph in Appendix C of SLAC: https://arxiv.org/pdf/1907.00953.pdf
# See Dreamer TF2's implementation: https://github.com/danijar/dreamer/blob/02f0210f5991c7710826ca7881f19c64a012290c/dreamer.py#L340
action_repeat: 1 #not used for now 
# train
num_train_steps: 5000000
num_train_iters: 1
num_seed_steps: 1000

# replay_buffer_capacity: 100000
seed: 10
# eval
eval_frequency: 10000
num_eval_episodes: 2
# misc
log_frequency_step: 10000
log_save_tb: true
save_video: true
device: cuda
# observation
image_size: 84
image_pad: 4
horizon: 500 #not used here
use_lowdim: true
# global params
lr: 1e-3
# IMPORTANT: please use a batch size of 512 to reproduce the results in the paper. Hovewer, with a smaller batch size it still works well.
batch_size: 128

#for save and loading 
eval_only: false
load_dir: 2021.03.16/103232_

system: sim #sim for the mujoco stuff, and "real" for franka

stack: 1

environmentName: IndicatorBoxBlock #IMPORTANT: this is the environment that is run 
# modalities: [robot0_eef_pos, robot0_gripper_qpos, robot0_gripper_qvel]
modalities: [object_sound, robot0_eef_pos, robot0_gripper_qpos, robot0_gripper_qvel]
cameraName: agentview_image
runName:  ${environmentName}_friction_${episodes}
stacked: true

#Other hyperparameters
episodeLength: 250 #150 for occluded block, 250 for pick place 
episodes: 50
recordFrq: 10
sparseProp: 0.75

#different names currently registered

#IndicatorBoxBlock
#BlockedPickPlace


#"ClothCube",
#"SoftBlock",
#"BoxBlock"
#"Lift"
#"MMLift" (all our multimodal testing goes here)

#modalities to choose from
# robot0_joint_pos_cos  :  (7,)
# robot0_joint_pos_sin  :  (7,)
# robot0_joint_vel  :  (7,)
# robot0_eef_pos  :  (3,)
# robot0_eef_quat  :  (4,)
# robot0_gripper_qpos  :  (2,)
# robot0_gripper_qvel  :  (2,)
# agentview_image  :  (84, 84, 3)
# cube_pos  :  (3,)
# cube_quat  :  (4,)
# gripper_to_cube_pos  :  (3,)
# gripper_force  :  (3,)
# gripper_tip_force: (3, ) #for the force at the tip of the gripper 
# gripper_torque  :  (3,)
# object_sound  :  (2,)
# robot0_proprio-state  :  (32,) CONCATENATED from cos, sin, vel, pos, quat, qpos, qvel
# image-state  :  (84, 84, 3) DON'T USE THIS, use agentview_image instead
# object-state  :  (18,)
# robot0_gripper_act_force
# robot0_gripper_joint_force


# agent configuration
agent:
  name: drq
  class: drq.DRQAgent
  params:
    obs_shape: ??? # to be specified later
    action_shape: ??? # to be specified later
    action_range: ??? # to be specified later
    lowdim_dim: ??? #to b e specified later
    device: ${device}
    encoder_cfg: ${encoder}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    discount: 0.99
    init_temperature: 0.1
    lr: ${lr}
    actor_update_frequency: 2
    critic_tau: 0.01
    critic_target_update_frequency: 2
    batch_size: ${batch_size}
    log_frequency: 20

critic:
  class: drq.Critic
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_dim: 1024
    hidden_depth: 2

actor:
  class: drq.Actor
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-10, 2]

encoder:
  class: drq.Encoder
  params:
      obs_shape: ${agent.params.obs_shape}
      feature_dim: 50
      lowdim_dim: ${agent.params.lowdim_dim}
      num_layers: 4
      num_filters: 32
      output_dim: 35
      output_logits: False

#name of the folder directory 


# hydra configuration
hydra:
  name: ${env}
  run:
    dir: ./demos/${runName}/
