name: multimodal
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch
  - cudatoolkit
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+git://github.com/facebookresearch/hydra@0.11_branch
    - pandas
    - ipdb
    - tqdm
    - pyaudio
    - torchvision==0.9.1
    - torchaudio==0.8.1
    - yapf
    - librosa
    - pyquaternion
    - sklearn
    - matplotlib
    - kornia

