# env
env: drq-robosuite
action_repeat: 1 #not used for now 
# train
num_train_iters: 1
num_seed_steps: 1000
replay_buffer_capacity: 100000 #not used 

# misc
log_frequency_step: 1000
log_save_tb: true
save_video: true
device: cuda
# observation
image_size: 84 #224 #84 
image_pad: 4
horizon: 500
use_lowdim: true
# global params
lr: 1e-3
# IMPORTANT: please use a batch size of 512 to reproduce the results in the paper. Hovewer, with a smaller batch size it still works well.


######Mode of operation########
#this eval_only will be phased out in favor of a specialied script that tests everything 
eval_only: False #this is for evaluation runs without training
checkpoint: 100000
orig_seed: ${seed}
load_folder: ${environmentName}_${number_demos}_${orig_seed}
# load_dir: ${load_folder}/corrections_aggressive/0_
load_dir: ${load_folder}/ABLATE_MEM/${checkpoint}_
balanced_batches: False

#balanced batch training after corrections 
priority: True #if this is true, we only train on the corrections (keep for the ablations)
corrections_file: ${load_folder}/corrections_aggressive/demos_finished.pkl #fill this in later 

#########################

#things that we can't change without breaking something  
actor_root: /iris/u/maxjdu/communal_results/
demo_root: /iris/u/maxjdu/communal_demos/
use_squashed: True #squashed vs not squashed distributions
lowdim_stack: 10
frame_stack: 3 
system: sim #sim for the mujoco stuff, and "real" for franka

#####RUN CHANGES HERE ############
#core adjustements 
seed: ??
number_demos: 50
demo_file: ${environmentName}_${number_demos}/demos.pkl
stack: 1 #used to be 10

#misc training parameters 
batch_size: 16 #used to be 32
num_train_steps: 110000
eval_frequency: 10000
num_eval_episodes: 20 # used to be 20
expert_workers: 4
correction_workers: 4

#environment parameters 
environmentName: BlockedPickPlace #IMPORTANT: this is the environment that is run 
modalities: [object_sound, robot0_eef_pos, robot0_gripper_qpos, robot0_gripper_qvel] #object sound is 6d 
cameraName: agentview_image

#logging 
# runName: ${load_folder}
runName: ${environmentName}SCRATCH_${number_demos}_${seed}
#####CHANGES END HERE ##########


#different names currently registered
#"BlockedPickPlace"
#"IndicatorBoxBlock"

#modalities to choose from
# robot0_joint_pos_cos  :  (7,)
# robot0_joint_pos_sin  :  (7,)
# robot0_joint_vel  :  (7,)
# robot0_eef_pos  :  (3,)
# robot0_eef_quat  :  (4,)
# robot0_gripper_qpos  :  (2,) #two values roughly identical but inverted. Larger number (0.038) indicates open, smaller number (~0) indicates closed
# robot0_gripper_qvel  :  (2,)
# agentview_image  :  (84, 84, 3)
# cube_pos  :  (3,)
# cube_quat  :  (4,)
# gripper_to_cube_pos  :  (3,)
# gripper_force  :  (3,)
# gripper_torque  :  (3,)
# object_sound  :  (2,)
# robot0_proprio-state  :  (32,) CONCATENATED from cos, sin, vel, pos, quat, qpos, qvel
# image-state  :  (84, 84, 3) DON'T USE THIS, use agentview_image instead
# object-state  :  (18,)

#sidenote: gripper is negative in the action, gripper closed is positive in the action 

# agent configuration
agent:
  name: drq
  class: core.drq_memory.DRQAgent
  params:
    obs_shape: ??? # to be specified later
    action_shape: ??? # to be specified later
    action_range: ??? # to be specified later
    lowdim_dim: ??? #to b e specified later
    device: ${device}
    encoder_cfg: ${encoder}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    discount: 0.99
    init_temperature: 0.1
    lr: ${lr}
    actor_update_frequency: 2
    critic_tau: 0.01
    critic_target_update_frequency: 2
    batch_size: ${batch_size}
    log_frequency: 20

critic:
  class: core.drq_memory.Critic
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_dim: 1024
    hidden_depth: 2

actor:
  class: core.drq_memory.Actor
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-6, -1]

encoder:
  class: core.drq_memory.Encoder
  params:
      obs_shape: ${agent.params.obs_shape}
      feature_dim: 50 #used to be 50
      lowdim_dim: ${agent.params.lowdim_dim}
      num_layers: 4
      num_filters: 32
      output_dim: 35
      output_logits: False

#name of the folder directory 

log_dir: /iris/u/maxjdu/communal_results/${runName}

# hydra configuration
hydra:
  name: ${env}
  run:
#     dir: ../../communal_results/${runName}_${seed}
#     dir: ./runs/BC/${runName}_${hydra.job.override_dirname}_debugging
    dir: ${log_dir}
#     dir: /iris/u/maxjdu/communal_results/${runName}_${seed}
